In [1]:
import pandas as pd
data=[1,3,4,6,7]
series=pd.Series(data)
print("series \n",series)

series
 0    1
1    3
2    4
3    6
4    7
dtype: int64

In [4]:
## create a series from dictionary
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [ ]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [2]:
##dataframe
## create a dataframe from a dictionary  of list
import pandas as pd
data={
    'name':['krish','john','jack'],
    'age':[24,56,34],
    'city':['bangalore','cheenai','flordia']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    name  age       city
0  krish   24  bangalore
1   john   56    cheenai
2   jack   34    flordia
<class 'pandas.core.frame.DataFrame'>

In [2]:
df=pd.read_csv('sales.csv')
df.head(5)#give first 5 detalis
df.tail(3)#give last 3 detalis

,id,first_name,last_name,email,phone,job_title,department,company,city,country,signup_date,plan_type,last_login,account_status,is_newsletter_subscriber
7,1031,Lucia,Bianchi,l.bianchi@design.it,+39-06-1234567,Art Director,Creative,StudioVogue,Rome,Italy,2021-12-01,Premium,2025-01-15 12:00:00,Inactive,False
8,1032,Ahmed,Mansour,a.mansour@dubai.ae,+971-4-123-4567,Sales Executive,Growth,DesertVentures,Dubai,UAE,2024-10-22,Basic,2025-02-04 08:30:00,Active,True
9,1033,Chloe,Dupont,c.dupont@fr-services.fr,+33-1-42-68-53-00,Marketing Lead,Marketing,BrandBoost,Paris,France,2023-05-09,Enterprise,2025-02-03 14:10:00,Active,True

In [8]:
df['department']

0       Engineering
1         Analytics
2           Product
3        People Ops
4    Infrastructure
5           Finance
6       IT Security
7          Creative
8            Growth
9         Marketing
Name: department, dtype: object

In [12]:
df.iloc[2][3]

C:\Users\hmssh\AppData\Local\Temp\ipykernel_22408\3169236189.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[2][3]

'mchen88@global.com'

In [13]:
df.at[1,'company']

'InsightCorp'

In [14]:
df.iat[2,2]

'Chen'

In [16]:
df['salary']=[1,2,3,4,5,6,7,8,9,10]
df

,id,first_name,last_name,email,phone,job_title,department,company,city,country,signup_date,plan_type,last_login,account_status,is_newsletter_subscriber,salary
0,1024,Jordan,Smith,j.smith@fake-email.com,+1-555-012-3456,Senior Developer,Engineering,TechFlow Solutions,San Francisco,USA,2024-05-12,Premium,2025-01-28 14:30:00,Active,True,1
1,1025,Elena,Rodriguez,e.rod@provider.net,+34-910-112-233,Data Scientist,Analytics,InsightCorp,Madrid,Spain,2023-11-05,Basic,2025-02-01 09:15:00,Active,False,2
2,1026,Marcus,Chen,mchen88@global.com,+65-6789-0123,UX Designer,Product,Pixel Perfect,Singapore,Singapore,2024-01-20,Premium,2025-02-03 18:45:00,Active,True,3
3,1027,Sarah,Jenkins,s.jenkins@webmail.org,+44-20-7946-0111,HR Manager,People Ops,StaffStream,London,UK,2022-08-14,Enterprise,2025-01-30 11:20:00,Suspended,True,4
4,1028,Yuki,Tanaka,y.tanaka@jp-corp.jp,+81-3-1234-5678,DevOps Engineer,Infrastructure,CloudScale,Tokyo,Japan,2024-06-30,Basic,2025-02-04 03:10:00,Active,False,5
5,1029,Amara,Okonjo,amara.o@fintech.io,+234-1-460-1234,Product Manager,Finance,PaySwift,Lagos,Nigeria,2023-03-12,Premium,2025-02-02 20:05:00,Active,True,6
6,1030,Hans,Mueller,h.mueller@de-tech.de,+49-30-123456,Security Analyst,IT Security,CyberGuard,Berlin,Germany,2024-09-18,Basic,2025-02-01 16:50:00,Active,True,7
7,1031,Lucia,Bianchi,l.bianchi@design.it,+39-06-1234567,Art Director,Creative,StudioVogue,Rome,Italy,2021-12-01,Premium,2025-01-15 12:00:00,Inactive,False,8
8,1032,Ahmed,Mansour,a.mansour@dubai.ae,+971-4-123-4567,Sales Executive,Growth,DesertVentures,Dubai,UAE,2024-10-22,Basic,2025-02-04 08:30:00,Active,True,9
9,1033,Chloe,Dupont,c.dupont@fr-services.fr,+33-1-42-68-53-00,Marketing Lead,Marketing,BrandBoost,Paris,France,2023-05-09,Enterprise,2025-02-03 14:10:00,Active,True,10

In [22]:
df.drop('salary',axis=1,inplace=True)
df

,id,first_name,last_name,email,phone,job_title,department,company,city,country,signup_date,plan_type,last_login,account_status,is_newsletter_subscriber
0,1024,Jordan,Smith,j.smith@fake-email.com,+1-555-012-3456,Senior Developer,Engineering,TechFlow Solutions,San Francisco,USA,2024-05-12,Premium,2025-01-28 14:30:00,Active,True
1,1025,Elena,Rodriguez,e.rod@provider.net,+34-910-112-233,Data Scientist,Analytics,InsightCorp,Madrid,Spain,2023-11-05,Basic,2025-02-01 09:15:00,Active,False
2,1026,Marcus,Chen,mchen88@global.com,+65-6789-0123,UX Designer,Product,Pixel Perfect,Singapore,Singapore,2024-01-20,Premium,2025-02-03 18:45:00,Active,True
3,1027,Sarah,Jenkins,s.jenkins@webmail.org,+44-20-7946-0111,HR Manager,People Ops,StaffStream,London,UK,2022-08-14,Enterprise,2025-01-30 11:20:00,Suspended,True
4,1028,Yuki,Tanaka,y.tanaka@jp-corp.jp,+81-3-1234-5678,DevOps Engineer,Infrastructure,CloudScale,Tokyo,Japan,2024-06-30,Basic,2025-02-04 03:10:00,Active,False
5,1029,Amara,Okonjo,amara.o@fintech.io,+234-1-460-1234,Product Manager,Finance,PaySwift,Lagos,Nigeria,2023-03-12,Premium,2025-02-02 20:05:00,Active,True
6,1030,Hans,Mueller,h.mueller@de-tech.de,+49-30-123456,Security Analyst,IT Security,CyberGuard,Berlin,Germany,2024-09-18,Basic,2025-02-01 16:50:00,Active,True
7,1031,Lucia,Bianchi,l.bianchi@design.it,+39-06-1234567,Art Director,Creative,StudioVogue,Rome,Italy,2021-12-01,Premium,2025-01-15 12:00:00,Inactive,False
8,1032,Ahmed,Mansour,a.mansour@dubai.ae,+971-4-123-4567,Sales Executive,Growth,DesertVentures,Dubai,UAE,2024-10-22,Basic,2025-02-04 08:30:00,Active,True
9,1033,Chloe,Dupont,c.dupont@fr-services.fr,+33-1-42-68-53-00,Marketing Lead,Marketing,BrandBoost,Paris,France,2023-05-09,Enterprise,2025-02-03 14:10:00,Active,True

In [27]:
df['age']=[23,34,56,67,89,12,34,56,78,56]
df['age']+=1
df

,id,first_name,last_name,email,phone,job_title,department,company,city,country,signup_date,plan_type,last_login,account_status,is_newsletter_subscriber,age
0,1024,Jordan,Smith,j.smith@fake-email.com,+1-555-012-3456,Senior Developer,Engineering,TechFlow Solutions,San Francisco,USA,2024-05-12,Premium,2025-01-28 14:30:00,Active,True,24
1,1025,Elena,Rodriguez,e.rod@provider.net,+34-910-112-233,Data Scientist,Analytics,InsightCorp,Madrid,Spain,2023-11-05,Basic,2025-02-01 09:15:00,Active,False,35
2,1026,Marcus,Chen,mchen88@global.com,+65-6789-0123,UX Designer,Product,Pixel Perfect,Singapore,Singapore,2024-01-20,Premium,2025-02-03 18:45:00,Active,True,57
3,1027,Sarah,Jenkins,s.jenkins@webmail.org,+44-20-7946-0111,HR Manager,People Ops,StaffStream,London,UK,2022-08-14,Enterprise,2025-01-30 11:20:00,Suspended,True,68
4,1028,Yuki,Tanaka,y.tanaka@jp-corp.jp,+81-3-1234-5678,DevOps Engineer,Infrastructure,CloudScale,Tokyo,Japan,2024-06-30,Basic,2025-02-04 03:10:00,Active,False,90
5,1029,Amara,Okonjo,amara.o@fintech.io,+234-1-460-1234,Product Manager,Finance,PaySwift,Lagos,Nigeria,2023-03-12,Premium,2025-02-02 20:05:00,Active,True,13
6,1030,Hans,Mueller,h.mueller@de-tech.de,+49-30-123456,Security Analyst,IT Security,CyberGuard,Berlin,Germany,2024-09-18,Basic,2025-02-01 16:50:00,Active,True,35
7,1031,Lucia,Bianchi,l.bianchi@design.it,+39-06-1234567,Art Director,Creative,StudioVogue,Rome,Italy,2021-12-01,Premium,2025-01-15 12:00:00,Inactive,False,57
8,1032,Ahmed,Mansour,a.mansour@dubai.ae,+971-4-123-4567,Sales Executive,Growth,DesertVentures,Dubai,UAE,2024-10-22,Basic,2025-02-04 08:30:00,Active,True,79
9,1033,Chloe,Dupont,c.dupont@fr-services.fr,+33-1-42-68-53-00,Marketing Lead,Marketing,BrandBoost,Paris,France,2023-05-09,Enterprise,2025-02-03 14:10:00,Active,True,57